apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: masterino-market-api-no-public-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: masterino-market
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - { protocol: TCP, port: 3220 }
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - { protocol: TCP, port: 5432 }
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - { protocol: TCP, port: 6379 }
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: masterino-market-oss
      ports:
        - { protocol: TCP, port: 9000 }
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: masterino-market-runner
      ports:
        - { protocol: TCP, port: 3221 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: masterino-market-runner-proxy-only-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: masterino-market-runner
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: masterino-market
      ports:
        - { protocol: TCP, port: 3221 }
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: connector-egress-proxy
      ports:
        - { protocol: TCP, port: 3128 }
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - { protocol: TCP, port: 5432 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
