apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: masterino
resources:
  - ../../base
  - auth-signup-ingress.yaml
  - namespace.yaml
  - configmap.yaml
  - device-gateway.yaml
  - ingress.yaml
  - metadata-egress-network-policy.yaml
  - oidc-token-ingress.yaml
  - pdb.yaml
  - storageclass.yaml
  - webapi-trace-ingress.yaml
replicas:
  - name: masterino
    count: 2
images:
  - name: boen-registry-vpc.cn-shenzhen.cr.aliyuncs.com/biel_client/masterino-device-gateway
    newName: boen-registry-vpc.cn-shenzhen.cr.aliyuncs.com/biel_client/masterino-device-gateway
    digest: sha256:bdb74578c3c8129d898bf628494afe0b7ff22bb0fcb7d62f9f8fdac50d5c463d
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: acr-credential-secret-aggregation
  - target:
      kind: Deployment
      name: masterino
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEVICE_GATEWAY_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: masterino-device-gateway-secret
              key: SERVICE_TOKEN
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: acr-credential-secret-aggregation
  - target:
      kind: StatefulSet
      name: masterino-postgres
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: masterino-production-essd-retain
  - target:
      kind: StatefulSet
      name: masterino-redis
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: masterino-production-essd-retain
