apiVersion: log.alibabacloud.com/v1alpha1
kind: AliyunLogConfig
metadata:
  name: masterino-product-events
spec:
  logstore: product-events
  shardCount: 2
  lifeCycle: 90
  logtailConfig:
    inputType: file
    configName: masterino-product-events
    inputDetail:
      dockerFile: true
      dockerIncludeLabel:
        app.kubernetes.io/name: masterino
      filePattern: product-events.jsonl
      logPath: /var/log/masterino
      logType: json_log
