AUTH_DISABLE_SIGNUP=true
CLICKHOUSE_CLUSTER_ENABLED=false
CLICKHOUSE_DB=default
CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
CLICKHOUSE_URL=http://clickhouse:8123
CLICKHOUSE_USER=langfuse
HOSTNAME=0.0.0.0
LANGFUSE_CSP_ENFORCE_HTTPS=true
LANGFUSE_INIT_ORG_ID=masterino
LANGFUSE_INIT_ORG_NAME=Masterino
LANGFUSE_INIT_PROJECT_ID=masterino-production
LANGFUSE_INIT_PROJECT_NAME=Masterino Production
LANGFUSE_INIT_PROJECT_RETENTION=90
LANGFUSE_LOG_FORMAT=json
LANGFUSE_S3_BATCH_EXPORT_ENABLED=true
LANGFUSE_S3_BATCH_EXPORT_BUCKET=masterino-langfuse-1574541762075655
LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=https://oss-cn-shenzhen.aliyuncs.com
LANGFUSE_S3_BATCH_EXPORT_PREFIX=exports/
LANGFUSE_S3_BATCH_EXPORT_REGION=cn-shenzhen
LANGFUSE_S3_EVENT_UPLOAD_BUCKET=masterino-langfuse-1574541762075655
LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=https://oss-cn-shenzhen.aliyuncs.com
LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
LANGFUSE_S3_EVENT_UPLOAD_REGION=cn-shenzhen
LANGFUSE_S3_EVENT_UPLOAD_SSE=AES256
LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=masterino-langfuse-1574541762075655
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=https://oss-cn-shenzhen.aliyuncs.com
LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/
LANGFUSE_S3_MEDIA_UPLOAD_REGION=cn-shenzhen
LANGFUSE_S3_MEDIA_UPLOAD_SSE=AES256
NEXTAUTH_URL=https://langfuse-internal.bielcrystal.com
REDIS_CLUSTER_ENABLED=false
REDIS_KEY_PREFIX=langfuse:
